// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFwuJlC3a92JSuUO-jF8dW678jgFLNWjc',
    appId: '1:512038740073:web:13e21e2e03f51f18f842f8',
    messagingSenderId: '512038740073',
    projectId: 'bombo1',
    authDomain: 'bombo1.firebaseapp.com',
    databaseURL: 'https://bombo1-default-rtdb.firebaseio.com',
    storageBucket: 'bombo1.appspot.com',
    measurementId: 'G-F1TJQFJX2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDcUppXm0IsX3K1nwtvurIstEt4Abfs0zo',
    appId: '1:512038740073:android:c3aeccff6de204d0f842f8',
    messagingSenderId: '512038740073',
    projectId: 'bombo1',
    databaseURL: 'https://bombo1-default-rtdb.firebaseio.com',
    storageBucket: 'bombo1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAm58Igwu5JZcPFqkAHmHTNwu1L0DV1bM',
    appId: '1:512038740073:ios:d96316f3732f0d53f842f8',
    messagingSenderId: '512038740073',
    projectId: 'bombo1',
    databaseURL: 'https://bombo1-default-rtdb.firebaseio.com',
    storageBucket: 'bombo1.appspot.com',
    iosClientId: '512038740073-ps6fnroci0c6s2b9ahqnp0t1sshn38e3.apps.googleusercontent.com',
    iosBundleId: 'com.example.driversApp',
  );
}
